# Generated by Django 2.2.1 on 2021-05-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulesstatus',
            name='modules',
            field=models.IntegerField(),
        ),
    ]
