# Generated by Django 2.2.1 on 2021-05-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210530_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='modules',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_modules', to='apis.Modules'),
            preserve_default=False,
        ),
    ]
